### ISSUE TITLE
interferes with lazygit navigation

### ISSUE THREAD

**Issue by thuvasooriya** [max397574/better-escape.nvim#81]
not sure which update made the specific change but, navigation in lazygit is very hard due to the j key getting escaped for every two presses. (there is no concept of normal mode there i guess).
a reliable solution would be great
will open a similar issue ticket in lazygit repository as well.

**Comment by max397574** [comment]
that's really weird
should have happened before the rewrite already

I'll investigate this
could perhaps be fixed by providing a `disabled` function which allows you disable it in certain contexts

**Comment by max397574** [comment]
well that's because since the rewrite you can also map things in terminal mode and there were defaults added
so you can just disable the terminal mappings if they are a problem for you

**Comment by thuvasooriya** [comment]
> well that's because since the rewrite you can also map things in terminal mode and there were defaults added so you can just disable the terminal mappings if they are a problem for you
```lua
  {
    "max397574/better-escape.nvim",
    event = "InsertEnter",
    -- lazy = false,
    config = function()
      require("better_escape").setup {
        default_mappings = false,
        mappings = {
          i = {
            j = {
              k = "<Esc>",
              j = "<Esc>",
            },
          },
          c = {
            j = {
              k = "<Esc>",
              j = "<Esc>",
            },
          },
          v = {
            j = {
              k = "<Esc>",
            },
          },
          s = {
            j = {
              k = "<Esc>",
            },
          },
        },
      }
    end,
  },
  ```
@max397574   i'm using the above configuration and the issue is still there. am i doing something wrong

**Comment by thuvasooriya** [comment]
alright the issue is gone after i update the plugin with lazygit, thankyou for your time.

**Comment by max397574** [comment]
glad I could help
hint: when enabling default mappings and setting the terminal ones (or just jj) to false the config will be way simpler

**Comment by cyaconi** [comment]
This worked for me
```lua
  {
    "max397574/better-escape.nvim",
    event = "InsertEnter",
    config = function()
      require("better_escape").setup({
        default_mappings = true,
        mappings = {
          t = { false },
        },
      })
    end,
  },
```

**Comment by thuvasooriya** [comment]
`t = {false},` didn't work for me for some reason, i settled on this config

  ```
  {
    "max397574/better-escape.nvim",
    event = "InsertEnter",
    config = function()
      require("better_escape").setup {
        mappings = {
          t = { j = { false } }, --lazygit navigation fix
          v = { j = { k = false } }, -- visual select fix
        },
      }
    end,
  },
```

**Comment by max397574** [comment]
`t = { false }` actually also wasn't intended to work
may also break in the future
